from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####


include: "rules/common.smk"
include: "rules/bam2bakr.smk"
include: "rules/features.smk"


if not config["bam2bakr"]:

    include: "rules/preprocess.smk"
    include: "rules/alignment.smk"
    include: "rules/rsem.smk"
    include: "rules/rsem_plus.smk"


# include: "rules/salmon.smk"


if config["features"]["exonic_bins"]:

    include: "rules/flatten.smk"


##### target rules #####


rule all:
    input:
        get_other_output(),
