from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### Impute potentially missing config parameters #####

if "lowRAM" not in config:
    config["lowRAM"] = False


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####


include: "rules/common.smk"
include: "rules/bam2bakr.smk"
include: "rules/features.smk"
include: "rules/lowram.smk"

# Print variables
onstart:
    print(f"Pipeline is starting...")
    print(f"COLS_TO_SUM: {COLS_TO_SUM}")
    print(f"cols_to_summarize: {cols_to_summarize}")
    print(f"SORTPARAMS: {key_args}")
    print(f"cols_to_search: {cols_to_search}")
    print(f"cols_to_sort: {cols_to_sort}")
    print(f"colnames: {colnames}")
    print(f"init_keepcols: {init_keepcols}")

if not config["bam2bakr"]:

    include: "rules/preprocess.smk"
    include: "rules/alignment.smk"
    include: "rules/rsem.smk"
    include: "rules/rsem_plus.smk"


# include: "rules/salmon.smk"


if config["features"]["exonic_bins"]:

    include: "rules/flatten.smk"


##### target rules #####


rule all:
    input:
        get_other_output(),
